"""
app/models/subtask.py
---------------------
A sub-item that belongs to a Task.

Completing a subtask awards the user 10 points.
When ALL subtasks of a task are completed, the task auto-completes and the
user earns a 50-point bonus (logic in the API layer).

Fields
------
id             — UUID PK
task_id        — FK → tasks.id (cascade delete)
title          — what to do
description    — optional notes / detail
status         — not_started | completed  (subtasks are binary, not in_progress)
estimated_time — minutes (supplied by Gemini in the AI breakdown)
ai_suggested   — True when this subtask was created by the AI breakdown endpoint
"""

import uuid
from sqlalchemy import Boolean, Column, Integer, String, Text, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.database.base import Base, TimestampMixin


class Subtask(Base, TimestampMixin):
    __tablename__ = "subtasks"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, nullable=False)
    task_id = Column(UUID(as_uuid=True), ForeignKey("tasks.id", ondelete="CASCADE"), nullable=False)

    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)

    # not_started | completed
    status = Column(String(20), nullable=False, default="not_started")

    # Estimated time in minutes (from Gemini AI)
    estimated_time = Column(Integer, nullable=True)

    # Was this subtask generated by AI?
    ai_suggested = Column(Boolean, nullable=False, default=False)

    # Custom point reward for completing this subtask (defaults to 10)
    points = Column(Integer, nullable=False, default=10)

    # Relationship back to parent task
    task = relationship("Task", back_populates="subtasks")

    def __repr__(self) -> str:
        return (
            f"<Subtask id={self.id} title={self.title!r} "
            f"status={self.status!r} ai={self.ai_suggested}>"
        )