"""
app/models/user.py
------------------
User account model.

Fields
------
id          — UUID primary key (generated by Python, not the DB)
email       — unique, indexed — used for login
username    — unique display name shown in the UI
password_hash — bcrypt hash, never the raw password

Relationships
-------------
tasks         — one-to-many; cascade-deletes tasks when user is deleted
gamification  — one-to-one record that tracks points / level
rewards       — one-to-many; cascade-deletes rewards when user is deleted
"""

import uuid
from sqlalchemy import Column, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.database.base import Base, TimestampMixin


class User(Base, TimestampMixin):
    __tablename__ = "users"

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )
    email = Column(String(255), unique=True, index=True, nullable=False)
    username = Column(String(100), unique=True, nullable=False)
    password_hash = Column(String(255), nullable=False)

    # Relationships
    tasks = relationship(
        "Task",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="select",
    )
    gamification = relationship(
        "UserGamification",
        back_populates="user",
        uselist=False,          # one-to-one
        cascade="all, delete-orphan",
        lazy="select",
    )
    rewards = relationship(
        "Reward",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="select",
    )

    def __repr__(self) -> str:
        return f"<User id={self.id} username={self.username!r}>"